import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import clsx from "clsx";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flareup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(GeistSans.className, GeistMono.variable)}>
        {children}
      </body>
    </html>
  );
}
